- type: tickit_devices.pneumatic.Pneumatic
  name: filter1
  inputs: {}
  initial_speed: 0.5
  initial_state: False
  ioc_name: PNEUMATIC
  db_file: src/tickit_devices/pneumatic/db_files/filter1.db
- type: tickit_devices.femto.Current
  name: current_device
  inputs: {}
  callback_period: 1000000000
- type: tickit_devices.femto.Femto
  name: femto
  inputs:
    input: current_device:output
  initial_gain: 2.5
  initial_current: 0.0
  db_file: src/tickit_devices/femto/record.db
  ioc_name: FEMTO
