# This is the individual part of the synchrotron - useful for tests but not much else
# For running use examples/configs/synchrotron.yaml

- tickit_devices.synchrotron.synchrotron_machine.SynchrotronMachineStatus:
    name: sync_machine
    inputs: {}
    port: 25564
- tickit.devices.sink.Sink:
    name: machine_sink
    inputs:
      input: sync_machine:mode