# This is the individual part of the synchrotron - useful for tests but not much else
#For running the full synchrotron use examples/configs/synchrotron.yaml

- tickit_devices.synchrotron.synchrotron_topup.SynchrotronTopUp:
    name: sync_topup
    inputs: {}
    port: 25563
    initial_countdown: 30
    initial_end_countdown: 40
    callback_period: 1e9
- tickit.devices.sink.Sink:
    name: topup_sink
    inputs:
      input: sync_topup:countdown